# Generated by Django 4.2.26 on 2025-11-17 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_collaboraterequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='image',
        ),
    ]
